Import('*')

SimObject('Hello.py')
SimObject('Memobj.py')
SimObject('SimpleCache.py')

Source('hello.cc')
Source('goodbye.cc')
Source('memobj.cc')
Source('simple_cache.cc')

DebugFlag('HelloDebug')
DebugFlag('Memobj')
DebugFlag('CacheDebug')
