Import('*')

SimObject('Hello.py')
SimObject('Memobj.py')
SimObject('CacheObj.py')

Source('hello.cc')
Source('goodbye.cc')
Source('memobj.cc')
Source('cache_obj.cc')

DebugFlag('HelloDebug')
DebugFlag('Memobj')
DebugFlag('CacheDebug')
